name: Build and Deploy

on:
  push:
    branches:
      - 11ty # Replace with your main branch name

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build # Replace with your build command

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
